//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace productAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productItem
    {
        public int productid { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public string type { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
